# Generated by Django 5.0.4 on 2024-05-14 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_location_skill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['created']},
        ),
    ]
