# Generated by Django 5.0.4 on 2024-05-16 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-vote_ratio', '-vote_total', 'title']},
        ),
    ]
